version: '3'

services:
  myservice:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-service
    restart: always
    tty: true
    ports:
      - "8080:8080"
    environment:
      - START_SLEEP=2
      - JAVA_OPTS=""
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-spring-app-network
    
networks:
  my-spring-app-network:

