version: '3'

services:

  ruby_rails_irb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails-irb
    network_mode: bridge
    restart: always
    depends_on:
     - db

  db:
    image: postgres:alpine
    restart: always
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
