FROM node:15.12.0-alpine3.10

WORKDIR /app


# https://docs.nestjs.com/
RUN npm i -g @nestjs/cli
# Создаем простой проект
RUN nest new example-app

WORKDIR /app/example-app

RUN npm install
# Build app with watch mode
# RUN nest build . -w

# Копируем его целиком во внешнюю папку /out  (должна быть примаунчена через docker run -v ...)
# CMD cp -r example-app/* /out/
CMD cp -r . /out/