FROM node:15.12.0-alpine3.10

WORKDIR /app

COPY ./app .
# ADD ./app .

# RUN install nestjs cli
RUN npm i -g @nestjs/cli

# USER node

EXPOSE 3000
EXPOSE 9229

# ENTRYPOINT [ "/bin/sh" ]
# CMD nest start debug --debug 0.0.0.0:9229 --watch
CMD nest start --debug 0.0.0.0:9229 --watch